[project]
name = "broadcast-unstake"
authors = ["Anonymous"]
description = "Decentralized token unstaking with advanced broadcasting capabilities"
telemetry = false
requirements = []
[contracts.stake-registry]
path = "contracts/stake-registry.clar"
depends_on = []

[contracts.unstake-broadcaster]
path = "contracts/unstake-broadcaster.clar"
depends_on = ["stake-registry"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
